//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvizZnanja.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KvizZnanjaEntities : DbContext
    {
        public KvizZnanjaEntities()
            : base("name=KvizZnanjaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kviz> Kvizs { get; set; }
        public virtual DbSet<KvizPitanje> KvizPitanjes { get; set; }
        public virtual DbSet<Odgovor> Odgovors { get; set; }
        public virtual DbSet<OdgovorPitanje> OdgovorPitanjes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Pitanje> Pitanjes { get; set; }
        public virtual DbSet<KvizRezultatOdgovor> KvizRezultatOdgovor { get; set; }
        public virtual DbSet<KvizRezultat> KvizRezultat { get; set; }
    }
}
