//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvizZnanja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KvizPitanje
    {
        public long ID { get; set; }
        public Nullable<long> KvizID { get; set; }
        public Nullable<long> PitanjeID { get; set; }
    }
}
