//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvizZnanja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KvizRezultat
    {
        public long ID { get; set; }
        public string NazivKviza { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> KvizID { get; set; }
        public Nullable<System.DateTime> DatumIVrijeme { get; set; }
        public string Score { get; set; }
        public Nullable<int> VrijemeTrajanja { get; set; }
        public Nullable<int> Tocnih { get; set; }
        public Nullable<int> Netocnih { get; set; }
        public Nullable<double> Postotak { get; set; }
    }
}
